<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestoreSources>$(MSBuildThisFileDirectory)</RestoreSources>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../../assets/branding/flower-petal/flower-petal.ico</ApplicationIcon>
    <AppHostDotNetSearch>Global</AppHostDotNetSearch>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.StartupHookProvider.IsSupported" Value="false" />
  </ItemGroup>
</Project>
